/**
 * GIF system for No Trace.
 *
 * Works with ZERO configuration:
 * - 27 built-in animated GIFs in `public/gifs/` (15 icons + 12 text
 *   reactions), generated by `scripts/make-gifs.sh` and
 *   `scripts/generate-gifs.sh`. Fully offline.
 * - 21 curated real GIFs served directly from Giphy's CDN
 *   (`https://i.giphy.com/<id>.gif`). These are plain image URLs, so they
 *   need no API key. Every ID in the list was verified to return a real
 *   GIF (not the "not found" placeholder).
 *
 * Message formats:
 * - `gif:<local-id>`            local pack (allow-listed)
 * - `gif:https://...`           remote GIF (validated host / extension)
 * - optional caption after `\n`
 *
 * If `GIPHY_API_KEY` is configured, `/api/gifs` also proxies live
 * trending/search results from GIPHY. Otherwise it serves the curated
 * pack (filtered when `q` is present).
 */

export type Gif = {
  id: string;
  label: string;
  src: string;
};

export type RemoteGif = {
  id: string;
  label: string;
  url: string;
  preview: string;
  tags: string[];
};

const make = (id: string, label: string): Gif => ({
  id,
  label,
  src: `/gifs/${id}.gif`,
});

/** Local animated pack (ships with the app, works offline). */
export const GIFS: Gif[] = [
  // Icon pack (96x96, transparent) — scripts/make-gifs.sh
  make("heart", "Amor"),
  make("fire", "Fuego"),
  make("laugh", "Risa"),
  make("cry", "Llanto"),
  make("sad", "Triste"),
  make("cool", "Cool"),
  make("thumbsup", "Me gusta"),
  make("thumbsdown", "No me gusta"),
  make("star", "Estrella"),
  make("rocket", "Cohete"),
  make("gift", "Regalo"),
  make("party", "Fiesta"),
  make("coffee", "Café"),
  make("moon", "Luna"),
  make("clock", "Tiempo"),
  // Text reactions (224x144) — scripts/generate-gifs.sh
  make("hola", "¡Hola!"),
  make("jaja", "Jaja"),
  make("wow", "¡Wow!"),
  make("si", "¡Sí!"),
  make("no", "¡Nooo!"),
  make("bravo", "¡Bravo!"),
  make("fiesta", "Fiesta"),
  make("gracias", "Gracias"),
  make("amor", "Amor"),
  make("vamos", "¡Vamos!"),
  make("ok", "¡OK!"),
  make("sorpresa", "¡OMG!"),
];

const giphy = (id: string, label: string, tags: string[]): RemoteGif => ({
  id,
  label,
  url: `https://i.giphy.com/${id}.gif`,
  preview: `https://i.giphy.com/${id}.gif`,
  tags,
});

/**
 * Curated real GIFs. Every ID below was verified (HTTP 200 + real GIF
 * bytes, hash differs from Giphy's "not found" placeholder).
 */
export const REMOTE_GIFS: RemoteGif[] = [
  giphy("dzaUX7CAG0Ihi", "Hola", ["hola", "hello", "hi", "oso", "bear", "saludo", "hey"]),
  giphy("xozcLYDOgWBbi", "Bien hecho", ["bien", "ok", "si", "yes", "pulgar", "thumbsup", "good", "like"]),
  giphy("10JhviFuU2gWD6", "Mucha risa", ["risa", "jaja", "lol", "laugh", "haha", "funny", "capitan"]),
  giphy("T3Vx6sVAXzuG4", "Bebé riendo", ["bebe", "baby", "risa", "laugh", "jaja", "lol", "cute", "lindo"]),
  giphy("11sBLVxNs7v6WA", "Minions", ["minions", "risa", "jaja", "lol", "laugh", "funny", "minion"]),
  giphy("a0h7sAqON67nO", "Gran éxito", ["exito", "success", "si", "yes", "bravo", "borat", "bien", "win", "ganar"]),
  giphy("l0HlvtIPzPdt2usKs", "Celebración", ["fiesta", "party", "celebracion", "celebration", "exito", "bravo", "yeah"]),
  giphy("l0MYt5jPR6QX5pnqM", "Fiesta en la oficina", ["oficina", "office", "fiesta", "party", "si", "yes", "trabajo", "yeah"]),
  giphy("3o7TKSjRrfIPjeiVyM", "Mente explotada", ["ciencia", "mente", "mind", "wow", "omg", "science", "sorpresa", "increible"]),
  giphy("d2lcHJTG5Tscg", "Llorando", ["llorar", "cry", "triste", "sad", "lagrimas", "no", "fail"]),
  giphy("JIX9t2j0ZTN9S", "Gato programador", ["gato", "cat", "trabajo", "work", "hacker", "programar", "ordenador", "laptop"]),
  giphy("13CoXDiaCcCoyk", "Gato asustado", ["gato", "cat", "miedo", "scared", "susto", "wow", "omg", "asustado"]),
  giphy("3o6Zt6ML6BklcajjsA", "Borrando el disco", ["gato", "cat", "error", "fail", "borrar", "oops", "ups", "fail"]),
  giphy("mlvseq9yvZhba", "Gato malo", ["gato", "cat", "enojo", "angry", "malo", "bad", "amenaza"]),
  giphy("3o7aD2saalBwwftBIY", "Viernes 13", ["gato", "cat", "viernes", "friday", "suerte", "luck", "negro", "black"]),
  giphy("2WuHHWbGt3fY4", "Trabajando", ["trabajo", "work", "oficina", "office", "ordenador", "computer", "concentrado"]),
  giphy("dOxMHecx24CY", "Cool", ["cool", "guapo", "hola", "hi", "hello", "chico", "guy"]),
  giphy("j1s5Sv4iolneE", "JIF vs GIF", ["jif", "gif", "debate", "lol", "funny", "gracioso"]),
  giphy("GB0lKzzxIv1te", "Niños bomberos", ["niños", "kids", "lol", "risa", "funny", "gracioso", "bomberos"]),
  giphy("xT9IgG50Fb7Mi0prBC", "Esfuerzo en la playa", ["playa", "beach", "esfuerzo", "trabajo", "work", "fuerza", "tirar"]),
  giphy("YsTs5ltWtEhnq", "Superman", ["superman", "heroe", "hero", "volar", "fly", "volando", "fuerte"]),
];

const BY_ID = new Map(GIFS.map((gif) => [gif.id, gif]));

export const GIF_PREFIX = "gif:";
export const GIF_IDS = GIFS.map((gif) => gif.id);

/** Hosts allowed for `gif:https://...` remote messages. */
export const REMOTE_GIF_HOSTS = [
  "i.giphy.com",
  "media.giphy.com",
  "media0.giphy.com",
  "media1.giphy.com",
  "media2.giphy.com",
  "media3.giphy.com",
  "media4.giphy.com",
  "giphy.com",
  "media.tenor.com",
  "c.tenor.com",
  "tenor.com",
  "media.klippy.com",
  "cdn.klippy.com",
] as const;

const REMOTE_HOST_SET = new Set<string>(REMOTE_GIF_HOSTS);

/** Max length for a remote GIF URL inside a message. */
export const MAX_REMOTE_GIF_URL_LEN = 500;

export function getGif(id: string): Gif | null {
  return BY_ID.get(id.trim()) ?? null;
}

export function isGifContent(content: string) {
  return content.startsWith(GIF_PREFIX);
}

/** Checks that a remote GIF URL is safe to store and render. */
export function isRemoteGifUrl(raw: string): boolean {
  const value = raw.trim();
  if (!value.startsWith("https://")) return false;
  if (value.length > MAX_REMOTE_GIF_URL_LEN) return false;
  if (/[\s"'<>]/.test(value)) return false;
  let parsed: URL;
  try {
    parsed = new URL(value);
  } catch {
    return false;
  }
  if (parsed.protocol !== "https:") return false;
  const host = parsed.hostname.toLowerCase();
  const knownHost = REMOTE_HOST_SET.has(host) || host.endsWith(".giphy.com") || host.endsWith(".tenor.com");
  // Known GIF CDNs: any path is fine (they serve GIFs at extensionless URLs too).
  if (knownHost) return true;
  // Unknown hosts: only direct image files.
  return /\.(gif|png|jpe?g|webp)(\?[^]*)?$/i.test(parsed.pathname + parsed.search);
}

export type ParsedGif = {
  /** Local pack GIF (when the id belongs to the bundled pack). */
  gif: Gif | null;
  /** Remote GIF URL (when `gif:https://...` passes validation). */
  remoteUrl: string | null;
  /** Optional caption after the first newline. */
  text: string;
};

/** Parses `gif:<id>` and `gif:<https-url>`, with optional `\n` caption. */
export function parseGif(content: string): ParsedGif {
  if (!isGifContent(content)) return { gif: null, remoteUrl: null, text: content };
  const newline = content.indexOf("\n");
  const head =
    newline === -1 ? content.slice(GIF_PREFIX.length) : content.slice(GIF_PREFIX.length, newline);
  const text = newline === -1 ? "" : content.slice(newline + 1);
  const id = head.trim();
  if (!id) return { gif: null, remoteUrl: null, text };
  const local = getGif(id);
  if (local) return { gif: local, remoteUrl: null, text };
  if (id.startsWith("https://") && isRemoteGifUrl(id)) {
    return { gif: null, remoteUrl: id, text };
  }
  return { gif: null, remoteUrl: null, text };
}

export function isValidGifContent(content: string): boolean {
  if (!isGifContent(content)) return false;
  if (content.length > MAX_REMOTE_GIF_URL_LEN + 200) return false;
  const parsed = parseGif(content);
  if (parsed.text.length > 500) return false;
  return parsed.gif !== null || parsed.remoteUrl !== null;
}

export const GIF_PATTERN = new RegExp(`^${GIF_PREFIX}[^\\n]{1,512}(\\n[\\s\\S]{0,500})?$`);

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

/** Searches the curated remote pack by label/tags (accent-insensitive). */
export function searchRemoteGifs(query: string, limit = 18): RemoteGif[] {
  const q = normalize(query.trim());
  if (!q) return REMOTE_GIFS.slice(0, limit);
  const words = q.split(/\s+/).filter(Boolean);
  const scored: { gif: RemoteGif; score: number }[] = [];
  for (const gif of REMOTE_GIFS) {
    const hay = normalize(`${gif.label} ${gif.tags.join(" ")}`);
    let score = 0;
    for (const word of words) {
      if (normalize(gif.label).includes(word)) score += 3;
      else if (gif.tags.some((tag) => normalize(tag).includes(word))) score += 2;
      else if (hay.includes(word)) score += 1;
      else {
        score = -1;
        break;
      }
    }
    if (score >= 0) scored.push({ gif, score });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((entry) => entry.gif);
}

/** Searches the local pack by label (accent-insensitive). */
export function searchLocalGifs(query: string): Gif[] {
  const q = normalize(query.trim());
  if (!q) return GIFS;
  return GIFS.filter((gif) => normalize(gif.label).includes(q) || normalize(gif.id).includes(q));
}
