/**
 * Built-in GIF pack.
 *
 * The animated GIF files live in `public/gifs/` and are generated by
 * `scripts/make-gifs.sh`. Everything ships with the app, so the system needs
 * no API key, no external service and works offline. Messages sent with a
 * GIF use the format `gif:<id>`.
 */

export type Gif = {
  id: string;
  label: string;
  src: string;
};

const make = (id: string, label: string): Gif => ({
  id,
  label,
  src: `/gifs/${id}.gif`,
});

export const GIFS: Gif[] = [
  make("heart", "Amor"),
  make("fire", "Fuego"),
  make("laugh", "Risa"),
  make("cry", "Llanto"),
  make("sad", "Triste"),
  make("cool", "Cool"),
  make("thumbsup", "Me gusta"),
  make("thumbsdown", "No me gusta"),
  make("star", "Estrella"),
  make("rocket", "Cohete"),
  make("gift", "Regalo"),
  make("party", "Fiesta"),
  make("coffee", "Café"),
  make("moon", "Luna"),
  make("clock", "Tiempo"),
];

const BY_ID = new Map(GIFS.map((gif) => [gif.id, gif]));

export const GIF_PREFIX = "gif:";
export const KLIPPY_PREFIX = "klippy:";
export const GIF_IDS = GIFS.map((gif) => gif.id);

export function getGif(id: string): Gif | null {
  return BY_ID.get(id.trim()) ?? null;
}

export function isGifContent(content: string) {
  return content.startsWith(GIF_PREFIX) || content.startsWith(KLIPPY_PREFIX);
}

/** Parses `gif:<id>` or `klippy:<url>` and returns the GIF data. */
export function parseGif(content: string): { gif: Gif | null; klippyUrl?: string; text: string } {
  if (!isGifContent(content)) return { gif: null, text: content };
  
  const newline = content.indexOf("\n");
  const isKlippy = content.startsWith(KLIPPY_PREFIX);
  const prefix = isKlippy ? KLIPPY_PREFIX : GIF_PREFIX;
  
  const id =
    newline === -1
      ? content.slice(prefix.length)
      : content.slice(prefix.length, newline);
  const text = newline === -1 ? "" : content.slice(newline + 1);
  
  if (isKlippy) {
    return { gif: null, klippyUrl: id, text };
  }
  
  return { gif: getGif(id), text };
}

export const GIF_PATTERN = new RegExp(
  `^(${GIF_PREFIX}[a-z0-9-]{1,24}|${KLIPPY_PREFIX}https?://[^\\s]+)(\\n[\\s\\S]*)?$`,
);
